"raise Exception('Intentional failure for testing')" 
